# Generated by Django 5.2.8 on 2025-11-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='PruebaBack', max_length=128),
            preserve_default=False,
        ),
    ]
